name: tournament_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl:
  easy_localization:
  firebase_core:
  firebase_auth:
  firebase_database:
  flutter_secure_storage:
  the_apple_sign_in:
  google_sign_in:
  date_formatter:
  provider:
  sign_in_with_apple:
  http:
  crypto:

dependency_overrides:
  intl:




dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: # Pour simuler des objets dans vos tests unitaires
  build_runner: # Nécessaire pour générer des mocks

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
