name: tournament_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_database: ^10.3.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  google_sign_in: ^6.1.5
  google_sign_in_android: ^6.1.20
  google_sign_in_ios: ^5.6.4
  the_apple_sign_in: ^1.1.1
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
