// Mocks generated by Mockito 5.4.5 from annotations
// in tournament_management/test/presenter/detailtournament_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:firebase_database/firebase_database.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:tournament_management/models/end_tournament.dart' as _i3;
import 'package:tournament_management/models/match.dart' as _i9;
import 'package:tournament_management/models/poule.dart' as _i5;
import 'package:tournament_management/models/tournament.dart' as _i2;
import 'package:tournament_management/pages/detail_tournament/detail_tournament_viewmodel.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTournamentDate_0 extends _i1.SmartFake
    implements _i2.TournamentDate {
  _FakeTournamentDate_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEndTournament_1 extends _i1.SmartFake implements _i3.EndTournament {
  _FakeEndTournament_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Tournament].
///
/// See the documentation for Mockito's code generation for more information.
class MockTournament extends _i1.Mock implements _i2.Tournament {
  MockTournament() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get sportEvent =>
      (super.noSuchMethod(
            Invocation.getter(#sportEvent),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#sportEvent),
            ),
          )
          as String);

  @override
  _i2.TournamentDate get tournamentDate =>
      (super.noSuchMethod(
            Invocation.getter(#tournamentDate),
            returnValue: _FakeTournamentDate_0(
              this,
              Invocation.getter(#tournamentDate),
            ),
          )
          as _i2.TournamentDate);

  @override
  String get createdBy =>
      (super.noSuchMethod(
            Invocation.getter(#createdBy),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#createdBy),
            ),
          )
          as String);

  @override
  List<String> get participants =>
      (super.noSuchMethod(
            Invocation.getter(#participants),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i5.Poule> get pouleList =>
      (super.noSuchMethod(
            Invocation.getter(#pouleList),
            returnValue: <_i5.Poule>[],
          )
          as List<_i5.Poule>);

  @override
  _i3.EndTournament get finalMatchList =>
      (super.noSuchMethod(
            Invocation.getter(#finalMatchList),
            returnValue: _FakeEndTournament_1(
              this,
              Invocation.getter(#finalMatchList),
            ),
          )
          as _i3.EndTournament);

  @override
  set finalMatchList(_i3.EndTournament? _finalMatchList) => super.noSuchMethod(
    Invocation.setter(#finalMatchList, _finalMatchList),
    returnValueForMissingStub: null,
  );

  @override
  void updatePoule(
    String? pouleToUpdate,
    String? player1,
    String? player2,
    String? score,
  ) => super.noSuchMethod(
    Invocation.method(#updatePoule, [pouleToUpdate, player1, player2, score]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DetailTournamentViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailTournamentViewModel extends _i1.Mock
    implements _i6.DetailTournamentViewModel {
  MockDetailTournamentViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> generatePoolsAndUpdateTournament(
    _i2.Tournament? tournament,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generatePoolsAndUpdateTournament, [tournament]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i5.Poule> generatePools(List<String>? userList) =>
      (super.noSuchMethod(
            Invocation.method(#generatePools, [userList]),
            returnValue: <_i5.Poule>[],
          )
          as List<_i5.Poule>);

  @override
  _i7.Future<void> updateMatch(
    _i8.DatabaseReference? selectedPouleRef,
    _i9.MatchTournament? newMatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMatch, [selectedPouleRef, newMatch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
