// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE0jrQAr3Tts5Rn-EavHnS0meqFUxyRs',
    appId: '1:77372019755:web:9f521efea5ad3c7f41466e',
    messagingSenderId: '77372019755',
    projectId: 'gestion-tournoi',
    authDomain: 'gestion-tournoi.firebaseapp.com',
    databaseURL: 'https://gestion-tournoi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestion-tournoi.appspot.com',
    measurementId: 'G-S6R6FQTR0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRE9cWnImxD5tAMXWM-Jdrya6vjoDXzo',
    appId: '1:77372019755:android:378f42f8e750d2cd41466e',
    messagingSenderId: '77372019755',
    projectId: 'gestion-tournoi',
    databaseURL: 'https://gestion-tournoi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestion-tournoi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmEI04rGgHyoREIchZrTJVv0KUXvwMd4',
    appId: '1:77372019755:ios:bbd6f9ec77883df141466e',
    messagingSenderId: '77372019755',
    projectId: 'gestion-tournoi',
    databaseURL: 'https://gestion-tournoi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestion-tournoi.appspot.com',
    androidClientId: '77372019755-vj6ak16sp30gsi5rc5ffmtfj1c0oqm58.apps.googleusercontent.com',
    iosClientId: '77372019755-n0l3f1cvlsijh80nkcv3kikc2eu1enhj.apps.googleusercontent.com',
    iosBundleId: 'com.jro.tournament',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmEI04rGgHyoREIchZrTJVv0KUXvwMd4',
    appId: '1:77372019755:ios:53ec8f564605f26241466e',
    messagingSenderId: '77372019755',
    projectId: 'gestion-tournoi',
    databaseURL: 'https://gestion-tournoi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestion-tournoi.appspot.com',
    androidClientId: '77372019755-vj6ak16sp30gsi5rc5ffmtfj1c0oqm58.apps.googleusercontent.com',
    iosClientId: '77372019755-8ug2fgr2i99i5rvnpfoa2k9ulkt3m8cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tournamentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCE0jrQAr3Tts5Rn-EavHnS0meqFUxyRs',
    appId: '1:77372019755:web:831bacfe18a1d03141466e',
    messagingSenderId: '77372019755',
    projectId: 'gestion-tournoi',
    authDomain: 'gestion-tournoi.firebaseapp.com',
    databaseURL: 'https://gestion-tournoi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestion-tournoi.appspot.com',
    measurementId: 'G-2JEBJ0PYH0',
  );
}
