# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :setup_signing do
    match(type: "appstore")
  end

  lane :build do
    setup_signing

    gym(
      scheme: "Runner",
      output_directory: "./build",
      output_name: "Runner.ipa",
      export_method: "app-store"
    )
  end

  lane :upload do
    build
    pilot(ipa: "./build/Runner.ipa")
  end

  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_PRIVATE_KEY"]
    )
    match(type: "appstore",
          git_url: "git@github.com:brakzog/ios_certif.git",
          readonly: false)# Récupère le provisioning profile
    
    gym
    upload_to_testflight
  end
  

  
end
