# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :setup_signing do
    match(type: "appstore")
  end

  lane :build do
    setup_signing

    gym(
      scheme: "Runner",
      output_directory: "./build",
      output_name: "Runner.ipa",
      export_method: "app-store"
    )
  end

  lane :upload do
    build
    pilot(ipa: "./build/Runner.ipa")
  end

  lane :release do
    app_store_connect_api_key(
      key_json_path: "./fastlane/api_key.json"
    )
  
    build_app(scheme: "Runner")
  
    upload_to_app_store(
      skip_app_version_update: true,  # Évite de modifier la version sur l'App Store
      submit_for_review: false        # Ne soumet pas pour validation
    )
  end
  

  
end
