name: Flutter CI

on:
  push:
    branches: [ "feature/v1.0" ]
  pull_request:
    branches: [ "feature/v1.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplacez par la version de Flutter que vous utilisez

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build-android:
    name: Build APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplacez par votre version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB (Play Store)
        run: flutter build appbundle --release

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS
    runs-on: macos-latest  # Xcode obligatoire pour iOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplace avec ta version

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          pod update Firebase/CoreOnly AppAuth GoogleSignIn
          pod install --repo-update
      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build iOS (Flutter)
        run: flutter build ios --release --no-codesign

      - name: Archive iOS App
        run: |
          mkdir -p build/ios
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/ios/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload iOS Archive
        uses: actions/upload-artifact@v3
        with:
          name: ios-archive
          path: build/ios/Runner.xcarchive
