name: Flutter CI

on:
  push:
    branches: [ "feature/v1.0" ]
  pull_request:
    branches: [ "feature/v1.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1  # Remplacez par la version de Flutter que vous utilisez

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

