name: Flutter CI

on:
  push:
    branches: [ "feature/v1.0" ]
  pull_request:
    branches: [ "feature/v1.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplacez par la version de Flutter que vous utilisez

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build-android:
    name: Build APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplacez par votre version

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS}}" >> android/key.properties


      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB (Play Store)
        run: flutter build appbundle --release

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS
    runs-on: macos-latest  # Xcode obligatoire pour iOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3  # Remplace avec ta version

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          pod update Firebase/CoreOnly AppAuth GoogleSignIn
          pod install --repo-update
      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane
     
      - name: Setup Git Credentials
        run: git config --global url."https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Set environment variables for Fastlane
        run: |
       
          echo "FASTLANE_SESSION=${{ secrets.FASTLANE_SESSION }}" >> $GITHUB_ENV
          echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> $GITHUB_ENV

      - name: Setup SSH for match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts


      - name: Build and upload app store
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Défini un mot de passe dans GitHub Secrets
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_PRIVATE_KEY: ${{ secrets.APP_STORE_PRIVATE_KEY }}
        run: |
          cd ios
          fastlane release


      - name: Cleanup Keychain
        if: always()
        run: security delete-keychain build.keychain




